name: 'Setup GStreamer'
description: 'Setup GStreamer in the environment'
author: 'Laerdal Labs, DC'
branding:
  color: 'red'
  icon:  'activity'
inputs:
  version:
    description: 'version number'
    required:    false
    default:     '1.22.7'
  arch:
    description: 'architecture (x86, x86_64)'
    required:    false
    default:     'x86_64'
  repoUrl:
    description: 'the location of the source repository'
    required:    false
    default:     'https://gitlab.freedesktop.org/gstreamer/gstreamer.git'
outputs:
  gstreamerPath:
    description: 'Installation path'
runs:
  using: 'node16'
  main: 'dist/index.js'
