name: 'Setup GStreamer'
description: 'Setup GStreamer in the environment'
author: 'Laerdal Labs, DC'
branding:
  color: 'red'
  icon:  'activity'
inputs:
  version:
    description: 'version number'
    required:    false
    default:     '1.22.7'
  arch:
    description: 'architecture (x86, x86_64)'
    required:    false
    default:     'x86_64'
  repoUrl:
    description: 'the location of the source repository'
    required:    false
    default:     'https://gitlab.freedesktop.org/gstreamer/cerbero.git'
  msiUrl:
    description: 'Optional override of the URL from which to download the Windows runtime msi installer'
    required: false
  devMsiUrl:
    description: 'Optional override of the URL from which to download the Windows development libraries msi installer'
    required: false
  buildRun:
    description: 'Optional input with the run number for the workflow'
    required: false
outputs:
  gstreamerPath:
    description: 'Installation path'
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
