name: 'Setup GStreamer'
description: 'Setup GStreamer in the environment'
author: 'Laerdal Labs, DC'
branding:
  color: 'red'
  icon:  'activity'
inputs:
  version:
    description: 'version number'
    required: false
    default: '1.18.4'
outputs:
  gstreamerX86Path:
    description: 'x86 Architecture Installation path'
  gstreamerX64Path:
    description: 'x64 Architecture Installation path'
runs:
  using: 'node12'
  main: 'dist/index.js'
