name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  units:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-2019', 'windows-2022', 'macos-12', 'ubuntu-20.04']
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-2019', 'windows-2022', 'macos-12', 'ubuntu-20.04']
        arch: ['x86', 'x86_64']
        exclude:
          - os:   'macos-12'
            arch: 'x86'
          - os:   'ubuntu-20.04'
            arch: 'x86'

    steps:
    - uses: actions/checkout@v4

    - name: Setup GStreamer with default version
      uses: ./
      with:
        arch: ${{ matrix.arch }}

    - name: Run gst-inspect --version
      run: |
        gst-inspect-1.0 --version
