name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  units:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ['windows', 'macos']
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ['windows', 'macos']
    steps:
    - uses: actions/checkout@v2

    - name: Setup GStreamer with default version
      id:   setup_gstreamer_default
      uses: ./

    - name: Echo output paths
      run: |
        echo "gstreamerX86Path: ${{ steps.setup_gstreamer_default.outputs.gstreamerX86Path }}"
        echo "gstreamerX64Path: ${{ steps.setup_gstreamer_default.outputs.gstreamerX64Path }}"

    - name: Run gst-inspect --version
      if: ${{ matrix.os == 'windows' }}
      env:
        GST_BIN_PATH: ${{ steps.setup_gstreamer_default.outputs.gstreamerX64Path }}\\bin
      run: ${{ env.GST_BIN_PATH }}\\gst-inspect-1.0.exe --version

    - name: Run gst-inspect --version
      if: ${{ matrix.os == 'macos' }}
      env:
        GST_BIN_PATH: ${{ steps.setup_gstreamer_default.outputs.gstreamerX64Path }}/Commands
      run: ${{ env.GST_BIN_PATH }}/gst-inspect-1.0 --version

