name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  units:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-2019', 'windows-2022', 'macos-12', 'ubuntu-20.04']
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-2019', 'windows-2022', 'macos-12', 'ubuntu-20.04']
        arch: ['x86', 'x86_64']
        buildSource: [true, false]
        exclude:
          - os:   'macos-12'
            arch: 'x86'
          - os:   'ubuntu-20.04'
            arch: 'x86'
          - os:   'macos-12'
            buildSource: true
          - os:   'ubuntu-20.04'
            buildSource: false

    steps:
    - uses: actions/checkout@v4

    - name: Install Python for Windows
      if: matrix.os == 'windows-2019' || matrix.os == 'windows-2022'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Meson and Ninja Dependencies for Windows
      if: matrix.os == 'windows-2019' || matrix.os == 'windows-2022'
      run: pip install setuptools meson ninja

    - name: Setup GStreamer with default version
      uses: ./
      with:
        arch: ${{ matrix.arch }}
        buildSource: ${{ matrix.buildSource }}

    - name: Run gst-inspect --version
      run: |
        gst-inspect-1.0 --version
